### ISSUE TITLE
Plugin class Enrico69\MagentoRedirectOnLogin\Plugin\Connect doesn't exist

### ISSUE THREAD

**Issue by Fred000777** [enrico69/magento2-redirect-on-login#1]
Hi Enrico,

I have installed your extension on  a multi-domain Magento 2.1.9 instance. It compiles without error. The backend work fine as well. However on the front end you will get an exception error message at the /customer/account/loginPost/ page.

Any help would be appreciated. thanks.

1 exception(s):
Exception #0 (InvalidArgumentException): Plugin class Enrico69\MagentoRedirectOnLogin\Plugin\Connect doesn't exist

Exception #0 (InvalidArgumentException): Plugin class Enrico69\MagentoRedirectOnLogin\Plugin\Connect doesn't exist
#0 /var/www/sub3.mambuy.com/vendor/magento/framework/Interception/PluginList/PluginList.php(250): Magento\Framework\Interception\PluginList\PluginList->_inheritPlugins('Magento\\Custome...')
#1 /var/www/sub3.mambuy.com/var/generation/Magento/Customer/Controller/Account/LoginPost/Interceptor.php(35): Magento\Framework\Interception\PluginList\PluginList->getNext('Magento\\Custome...', 'dispatch')
#2 /var/www/sub3.mambuy.com/vendor/magento/framework/App/FrontController.php(55): Magento\Customer\Controller\Account\LoginPost\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#3 /var/www/sub3.mambuy.com/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#4 /var/www/sub3.mambuy.com/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#5 /var/www/sub3.mambuy.com/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#6 /var/www/sub3.mambuy.com/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#7 /var/www/sub3.mambuy.com/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#8 /var/www/sub3.mambuy.com/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#9 /var/www/sub3.mambuy.com/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#10 /var/www/sub3.mambuy.com/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#11 /var/www/sub3.mambuy.com/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#12 /var/www/sub3.mambuy.com/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#13 /var/www/sub3.mambuy.com/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#14 /var/www/sub3.mambuy.com/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#15 /var/www/sub3.mambuy.com/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(68): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#16 /var/www/sub3.mambuy.com/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#17 /var/www/sub3.mambuy.com/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#18 /var/www/sub3.mambuy.com/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#19 /var/www/sub3.mambuy.com/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#20 /var/www/sub3.mambuy.com/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#21 {main}

**Comment by enrico69** [comment]
Hi @Fred000777 

Honestly I have never officially "released" this module, I only developed it for some tests, which however were successful.

I will however try to help you.
How did you installed the module, and where? Please check that the files are in _app/code/Enrico69/MagentoRedirectOnLogin_.

Regards
